# Note: the namespace handler class is automatically generated by the build.
<#list classes as class>
${class.getNamespaceUri().replace(":", "\\:")}=${class.getNamespaceHandlerPackage()}.${class.getNamespaceHandlerName()}
</#list>
