# Note: the schema is automatically generated by the build.
http\://www.mulesoft.org/schema/mule/${class.getNamespacePrefix()}/${schemaVersion}/mule-${class.getNamespacePrefix()}.xsd=META-INF/mule-${class.getNamespacePrefix()}.xsd
