//
// THIS FILE WAS AUTOMATICALLY GENERATED BY MULESOFT CLOUD CONNECTOR DEVELOPMENT KIT. DO NOT EDIT MANUALLY.
//
package ${packageName};

import org.mule.config.spring.handlers.AbstractPojoNamespaceHandler;
import org.mule.config.spring.parsers.specific.InvokerMessageProcessorDefinitionParser;

import ${javaClass.getPackage()}.${javaClass.getName()};

public class ${className} extends AbstractPojoNamespaceHandler
{
    public void init()
    {
        <#if hasSetters>
        registerPojo("config", ${javaClass.getName()}.class);
        </#if>

        InvokerMessageProcessorDefinitionParser parser = null;

        <#list methods as method>
        parser = new InvokerMessageProcessorDefinitionParser("messageProcessor",
            ${className}.class, "${method.getName()}", new String[] {
             <#list method.getParameters() as parameter>
                "${parameter.getName()}"<#if parameter_has_next>,</#if>
             </#list>
            } );
        registerMuleBeanDefinitionParser( "<@splitCamelCase>${method.getName()}</@splitCamelCase>", parser );
        </#list>
    }
}
