# Note: the schema is automatically generated by the build.
http\://www.mulesoft.org/schema/mule/${namespaceIdentifierSuffix}/3.1/mule-${namespaceIdentifierSuffix}.xsd=META-INF/mule-${namespaceIdentifierSuffix}.xsd
