/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
#set($D='$')
#set($cloudServiceLower = "${cloudService.toLowerCase()}")
package ${package};

import org.mule.tools.cloudconnect.annotations.Connector;
import org.mule.tools.cloudconnect.annotations.Operation;

@Connector(namespacePrefix="${cloudServiceLower}")
public class ${cloudService}CloudConnector
{
    /*
     * The following is a sample operation
     */
    @Operation
    public void myOperation()
    {
    }
}
